markdown: enhanced_kramdown
pygments: true
lsi: false
safe: false
baseurl: /quasar

kramdown:
  use_coderay: false

## Site globals used throughout docs.
project: Quasar
github: puniverse/quasar
google_group: "https://groups.google.com/forum/#!forum/quasar-pulsar-user"
ga_tracking_id: UA-25007319-2


